### ISSUE TITLE
resolv.conf updated and error during installation

### ISSUE THREAD

**Issue by azhararain** [ocp-power-automation/ocp4-upi-powervm#86] opened 2020-08-06 08:16 UTC
I am facing an issue using "ocp4-upi-powervm" ... It creates the Bastion node and successfully ssh inside it and then throws the following error:

module.bastion.null_resource.bastion_packages (remote-exec):   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fff9088ca90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/ansible/

module.bastion.null_resource.bastion_packages (remote-exec):   Could not find a version that satisfies the requirement ansible (from versions: )
module.bastion.null_resource.bastion_packages (remote-exec): No matching distribution found for ansible

Error: error executing "/tmp/terraform_1645836036.sh": Process exited with status 1

I've looked into it, it seems that my /etc/resolv.conf is updated on the Bastion node and then it cannot resolve any domain as my DNS has been removed.

If in var.tfvars I provide: cluster_domain = "nip.io" ; it replaces my resolv.conf with: "search nip.io" ; whatever I provide in cluster_domain is replaced in resolv.conf and then resolution stops working for the Bastion node

My original resolv.conf has: "nameserver x.x.x.x" , this line is removed.

**Comment by yussufsh** [comment] 2020-08-06 12:25
After discussion with @azhararain found that the issue is because NetworkManager updates the domain name in resolv.conf when we set static hostname via `hostnamectl`.

The image is using cloud-init module set_hostname_from_dns which won't have  NM config which do not update the domain name when hostname is set.
```
# cat /etc/NetworkManager/conf.d/99-cloud-init.conf
# Created by cloud-init on instance boot automatically, do not edit.
#
[main]
dns = none
```
Since there is no DNS for setting hostname via reverse proxy asked him to use [these modules](https://github.com/ocp-power-automation/infra/blob/master/scripts/images/convert_qcow2_ova.py#L150-L151) instead

**Comment by bpradipt** [comment] 2020-08-13 11:55
@azhararain @yussufsh can we close this ?

**Comment by yussufsh** [comment] 2020-08-28 05:43
Issue was the resolv.conf updated when hostname was set because of the cloud-int-modules Azhar was using. Closing this.

**Closed as completed by yussufsh** 2020-08-28 05:43 UTC
